name = "tourmalinetech"  # Matches your Pages project name
pages_build_output_dir = "./dist"  # Adjust to your site's build output (e.g., "./public" for plain HTML/JS)
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]  # For Stripe's Node.js-like APIs

[vars]
# Optional: Hardcode non-secrets here (but prefer dashboard secrets for STRIPE_KEY, etc.)

# KV binding example for stock caching (create KV namespace in dashboard, then bind here)
[[kv_namespaces]]
binding = "STOCK_CACHE"
id = "your-kv-namespace-id"  # From Cloudflare > KV > Create Namespace > Copy ID

# D1 binding if you add a DB later (e.g., for order storage)
# [[d1_databases]]
# binding = "DB"
# database_name = "orders"
# database_id = "your-d1-id"
