name = "tourmalinetech"  # Matches your Pages project
pages_build_output_dir = "."  # Root dir for static files
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]  # Enables Stripe deps

# Env vars (use dashboard for secrets like STRIPE_KEY)
[vars]

# Optional KV for stock caching (create/bind in dashboard > KV)
[[kv_namespaces]]
binding = "STOCK_CACHE"
id = "your-kv-id-here"  # Replace after creating

# Optional D1 DB for orders
# [[d1_databases]]
# binding = "DB"
# database_name = "tourmaline-orders"
# database_id = "your-d1-id"
